/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author DELL
 */
public class trangChu extends javax.swing.JFrame {

    /**
     * Creates new form trangChu
     */
    public trangChu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButtonnhanvien = new javax.swing.JButton();
        jButtonxevao = new javax.swing.JButton();
        jButtonxera = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldvitritrong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldxetrongbai = new javax.swing.JTextField();
        jLabelbiensoxe = new javax.swing.JLabel();
        jTextFieldbiensoxe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreatimkiem = new javax.swing.JTextArea();
        buttonclear = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý bãi gửi xe");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trang chủ");

        jButtonnhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonnhanvien.setText("Quản lý nhân viên");
        jButtonnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnhanvienActionPerformed(evt);
            }
        });

        jButtonxevao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonxevao.setText("Quản lý xe vào bãi");
        jButtonxevao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxevaoActionPerformed(evt);
            }
        });

        jButtonxera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonxera.setText("Quản lý xe ra khỏi bãi");
        jButtonxera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxeraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số vị trí trống:");

        jTextFieldvitritrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvitritrongActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số xe trong bãi:");

        jTextFieldxetrongbai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldxetrongbaiActionPerformed(evt);
            }
        });

        jLabelbiensoxe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelbiensoxe.setText("Biển số xe:");

        jTextFieldbiensoxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldbiensoxeMouseClicked(evt);
            }
        });
        jTextFieldbiensoxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbiensoxeActionPerformed(evt);
            }
        });

        jTextAreatimkiem.setColumns(20);
        jTextAreatimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreatimkiem.setRows(5);
        jTextAreatimkiem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextAreatimkiemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextAreatimkiem);

        buttonclear.setText("Clear");
        buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonnhanvien)
                .addGap(118, 118, 118)
                .addComponent(jButtonxevao, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonxera)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabelbiensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldvitritrong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldxetrongbai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldbiensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(buttonclear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonxevao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonxera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldvitritrong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldxetrongbai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldbiensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelbiensoxe))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonclear)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnhanvienActionPerformed
        close();
        quanLyNhanVien pi = new quanLyNhanVien();

        pi.setVisible(true);

    }//GEN-LAST:event_jButtonnhanvienActionPerformed

    private void jButtonxevaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxevaoActionPerformed
        close();
        quanLyXeVao pi = new quanLyXeVao();
        pi.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonxevaoActionPerformed

    private void jButtonxeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxeraActionPerformed
        close();
        quanLyXeRa pi = new quanLyXeRa();
        pi.setVisible(true);
    }//GEN-LAST:event_jButtonxeraActionPerformed

    private void jTextFieldvitritrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvitritrongActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvitritrongActionPerformed

    private void jTextFieldxetrongbaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldxetrongbaiActionPerformed

        // TODO add your handling code here
    }//GEN-LAST:event_jTextFieldxetrongbaiActionPerformed

    private void jTextFieldbiensoxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbiensoxeActionPerformed
        String bienSoXe = jTextFieldbiensoxe.getText();
        String viTri = timKiemViTriXe(bienSoXe);
        if (viTri == null) {
            jTextAreatimkiem.setText("Không tìm thấy xe có biển số " + bienSoXe);
        }
        if (bienSoXe.isEmpty()) {
            jTextAreatimkiem.setText("Hãy nhập biển số xe");
        }

    }//GEN-LAST:event_jTextFieldbiensoxeActionPerformed

    private void jTextAreatimkiemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextAreatimkiemAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextAreatimkiemAncestorAdded

    private void buttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearActionPerformed
        jTextAreatimkiem.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonclearActionPerformed

    private void jTextFieldbiensoxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldbiensoxeMouseClicked
        jTextFieldbiensoxe.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbiensoxeMouseClicked

        private String timKiemViTriXe(String bienSoXe) {
            String viTri = null;
            return null;
        }

        public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(() -> {
                new trangChu().setVisible(true);
            });

        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonclear;
    private javax.swing.JButton jButtonnhanvien;
    private javax.swing.JButton jButtonxera;
    private javax.swing.JButton jButtonxevao;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelbiensoxe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreatimkiem;
    private javax.swing.JTextField jTextFieldbiensoxe;
    private javax.swing.JTextField jTextFieldvitritrong;
    private javax.swing.JTextField jTextFieldxetrongbai;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

}
